### ISSUE TITLE
Resources usage seem a bit excessive

### ISSUE THREAD

**Issue by ricardonunosr** [jakemason/abbrv#4]
CPU: `i5-11400F @ 2,60GHz`
GPU: `NVIDIA GeForce GTX 1050 Ti` with driver `527.37`

I think a simple app like this one should be less taxing on my poor old GPU :(
Happens even when minimized and not being rendered.

Screenshot:
![image](https://user-images.githubusercontent.com/47164756/209225971-b65fcc35-9f4c-422f-ae5b-d11ce1940441.png)

**Comment by jakemason** [comment]
@ricardonunosr Wow, that's _wild_. There's no reason I can think of that it'd be that high.

For reference here's mine, albeit on a `3090`:

![usage](https://user-images.githubusercontent.com/12981369/209229054-d258405c-fcc3-4bc9-81a3-4de4c79c91a6.png)

That's also only when the app is expanded and on the screen. Minimized it drops to ~0.2.

The only thing `abbrv` does that should use the GPU is open an OpenGL context and render Dear Imgui so I've got to imagine this is some weird driver error, maybe?

What's the use on the GPU while `abbrv` is minimized?

**Comment by jakemason** [comment]
@ricardonunosr Some Googling suggests this is [a driver error](https://www.reddit.com/r/Windows11/comments/ybswmq/gpu_utilization_at_100_after_latest_update/).

I realized I was on an older driver so I updated to `527.56` and get exactly what you're seeing but with 0% utilization in HW Monitor:
![drivers_yay](https://user-images.githubusercontent.com/12981369/209233090-3fd7e62b-c9f6-4423-bc4d-9cef0a6dc79c.png)

So, I downgraded back to `517.48` and the issue goes away entirely:

![older_drivers](https://user-images.githubusercontent.com/12981369/209233114-6a84a112-b004-44a3-89fd-db43b3249033.png)

Feel free to ask questions or follow up if you have any more information to report, but I'm 99% sure this is a driver error as my downgrade fixed it entirely.

**Comment by ricardonunosr** [comment]
@jakemason you are completely right 💯. ugh, it's just a shame that happens because I don't really wanna downgrade the driver. Thanks for the quick response 🥇

**Comment by jakemason** [comment]
@ricardonunosr Yeah, no problem! Thanks for trying `abbrv`! Let's hope NVIDIA fixes the bug soon :)
